# Generated by Django 5.0.6 on 2024-06-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth',
            new_name='Autoras',
        ),
        migrations.RenameModel(
            old_name='Colab',
            new_name='Colaboradores',
        ),
    ]
