# Generated by Django 5.0.6 on 2024-06-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
